### ISSUE TITLE
Wilton buffet update --- 5-3_to_6-5.md

### ISSUE THREAD

**Issue by hennalVEVO** [AverageCakeSlice/Persona-5-Royal-Differences#1]
The Wilton Hotel Buffet has been updated, with new lighting and textures. Comparison here: https://i.imgur.com/RQXJsDy.png Apologies for resolution.

Submitted here because I have no clue how to use GitHub.
--- /u/DerpDepartment

**Comment by AverageCakeSlice** [comment]
Oh, good catch, I'll add this in!

**Comment by AverageCakeSlice** [comment]
Added as per commit `b3e2b24`
